Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using XanElectronics.Dal;
using XanElectronics.Extentions;
using XanElectronics.Helpers;
using XanElectronics.Models;
using XanElectronics.ViewModels;

namespace XanElectronics.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BannerController : Controller
    {

        private readonly DataContext _context;
        private readonly IHostingEnvironment _env;
        public BannerController(DataContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_context.Banners.ToList());
        }



        public IActionResult Create()
        {
            if (_context.Banners.Count() >= 5)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Banner banner)
        {

            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!banner.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                return View();
            }

            if (banner.Photo.MaxLength(2000))
            {
                ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                return View();
            }

            if (_context.Sliders.Count() >= 5)
            {
                return RedirectToAction(nameof(Index));
            }
            string path = Path.Combine("assets", "img", "banner");
            string fileName = await banner.Photo.SaveImg(_env.WebRootPath, path);

            Banner newslider = new Banner();
            newslider.Image = fileName;

            await _context.Banners.AddAsync(newslider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Banner slider = await _context.Banners.FindAsync(id);
            if (slider == null) return NotFound();
            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null) return NotFound();
            Banner slider = await _context.Banners.FindAsync(id);
            if (slider == null) return NotFound();
            string path = Path.Combine("assets", "img", "banner");
            Helper.DeleteImage(_env.WebRootPath, path, slider.Image);

            _context.Banners.Remove(slider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();
            var banner = await _context.Banners.FindAsync(id);
            if (banner == null) return NotFound();
            return View(banner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, CreateBannerVM createBannerVM)
        {
            if (id == null) return NotFound();
            var dbBanner = await _context.Banners.FindAsync(id);
            if (dbBanner == null) return NotFound();
            if (createBannerVM.Photo != null)
            {
                if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    return View();
                }

                if (!createBannerVM.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                    return View();
                }

                if (createBannerVM.Photo.MaxLength(200))
                {
                    ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                    return View();
                }


                string path = Path.Combine("assets", "img", "banner");
                Helper.DeleteImage(_env.WebRootPath, path, dbBanner.Image);


                string fileName = await createBannerVM.Photo.SaveImg(_env.WebRootPath, path);
                dbBanner.Image = fileName;

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Controllers/BrandController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using XanElectronics.Dal;
using XanElectronics.Extentions;
using XanElectronics.Helpers;
using XanElectronics.Models;
using XanElectronics.ViewModels;

namespace XanElectronics.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _env;

        public BrandController(DataContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        // GET
        public IActionResult Index()
        {
            return View(_context.Brands.Where(x=>x.IsDeleted==false).ToList());
        }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrandCreateVM brandCreateVM)
        {
            if (!ModelState.IsValid) return View();

            if (ModelState["Image"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!brandCreateVM.Image.IsImage())
            {
                ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                return View();
            }

            if (brandCreateVM.Image.MaxLength(200))
            {
                ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                return View();
            }


            string path = Path.Combine("assets", "img", "brand");
            string fileName = await brandCreateVM.Image.SaveImg(_env.WebRootPath, path);

            bool existName = _context.Brands.Any(c => c.Name.ToLower().Trim() == brandCreateVM.Name.ToLower().Trim());
            if (existName)
            {
                ModelState.AddModelError("Name", "This brand exists");
                return View();
            }

            var newBrand = new Brand
            {
                Name = brandCreateVM.Name.ToLower(),
                ImageUrl= fileName
            };

            await _context.AddAsync(newBrand);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public  IActionResult Update(int? id)
        {
            if (id == null) return NotFound();
            var dbBrand =  _context.Brands.FirstOrDefault(c=>c.Id == id);
            if (dbBrand == null) return NotFound();
            return View(dbBrand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, BrandUpdateVM brandUpdateVM)
        {

            if (id == null) return NotFound();
            var dbBrand =  _context.Brands.FirstOrDefault(c=>c.Id == id);
            if (dbBrand == null) return NotFound();

            if (!ModelState.IsValid) return View();

            if (brandUpdateVM.Image!=null)
            {
                if (ModelState["Image"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    return View();
                }

                if (!brandUpdateVM.Image.IsImage())
                {
                    ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                    return View();
                }

                if (brandUpdateVM.Image.MaxLength(2000))
                {
                    ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                    return View();
                }


                string path = Path.Combine("assets", "img", "brand");
                Helper.DeleteImage(_env.WebRootPath, path, dbBrand.ImageUrl);
                string fileName = await brandUpdateVM.Image.SaveImg(_env.WebRootPath, path);

                dbBrand.ImageUrl = fileName;
            }

            var existBrand =  _context.Brands.FirstOrDefault(x=>x.Name == brandUpdateVM.Name);
            if(existBrand!= null)
            {
                if(dbBrand != existBrand)
                {
                    ModelState.AddModelError("Name", "Bu adda Brand movcuddur");
                    return View();
                }
            }

            dbBrand.Name = brandUpdateVM.Name;
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var brand = _context.Brands.FirstOrDefault(c => c.Id == id);
            if (brand == null) return NotFound();
            brand.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Areas/Admin/Controllers/SaleController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using XanElectronics.Dal;

namespace XanElectronics.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SaleController : Controller
    {
        private readonly DataContext _context;

        public SaleController(DataContext context)
        {
            _context = context;
        }
        
        // GET
        public IActionResult Index()
        {
            return View(_context.Sales.Where(x=>x.IsFinished==false).Include(s=>s.AppUser).OrderByDescending(x=>x.Id).ToList());
            
        }
        
        public IActionResult FinishedSales()
        {
            return View(_context.Sales.Where(x=>x.IsFinished==true).Include(s=>s.AppUser).OrderByDescending(x=>x.Id).ToList());
            
        }
        
        public async Task<IActionResult> Deactive(int? id)
        {
            if (id == null) return BadRequest();
            var sale = _context.Sales.FirstOrDefault(x => x.Id == id);
            if (sale == null) return BadRequest();
            sale.IsFinished = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound();
            var sale = _context.Sales.Include(s=>s.SaleProducts)
                .ThenInclude(s=>s.Product).FirstOrDefault(p => p.Id == id);
            if (sale == null) return NotFound();
            return View(sale);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var sale = _context.Sales.FirstOrDefault(x => x.Id == id);
            if (sale == null) return NotFound();
            _context.Sales.Remove(sale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(FinishedSales));
        }
    }
}

Areas/Admin/Controllers/SliderController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using XanElectronics.Dal;
using XanElectronics.Extentions;
using XanElectronics.Helpers;
using XanElectronics.Models;
using XanElectronics.ViewModels;

namespace XanElectronics.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {

        private readonly DataContext _context;
        private readonly IHostingEnvironment _env;
        public SliderController(DataContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
             return View(_context.Sliders.ToList());
        }
        
       

        public IActionResult Create()
        {
            if (_context.Sliders.Count() >= 5)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create(Slider slider)
        {
           
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!slider.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                return View();
            }

            if (slider.Photo.MaxLength(2000))
            {
                ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                return View();
            }

            if (_context.Sliders.Count() >= 5)
            {
                return RedirectToAction(nameof(Index));
            }
            string path = Path.Combine("assets","img", "slider");
            string fileName = await slider.Photo.SaveImg(_env.WebRootPath, path);
            
            Slider newslider = new Slider();
            newslider.Description= slider.Description;          
            newslider.Title = slider.Title;
            newslider.Image = fileName;
            
            await _context.Sliders.AddAsync(newslider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Slider slider = await _context.Sliders.FindAsync(id);
            if (slider == null) return NotFound();
            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null) return NotFound();
            Slider slider = await _context.Sliders.FindAsync(id);
            if (slider == null) return NotFound();
            string path = Path.Combine("assets","img", "slider");
            Helper.DeleteImage(_env.WebRootPath, path, slider.Image);

            _context.Sliders.Remove(slider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();
            Slider slider = await _context.Sliders.FindAsync(id);
            if (slider == null) return NotFound();
            return View(slider);
        }

         [HttpPost]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> Update(int? id, CreateSliderVM createSliderVM)
         {
             if (id == null) return NotFound();
             Slider dbSlider = await _context.Sliders.FindAsync(id);
             if (dbSlider == null) return NotFound();
             if (createSliderVM.Photo != null)
             {
                 if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                 {
                     return View();
                 }
        
                 if (!createSliderVM.Photo.IsImage())
                 {
                     ModelState.AddModelError("Photo", "Zehmet olmasa shekil formati sechin");
                     return View();
                 }
        
                 if (createSliderVM.Photo.MaxLength(200))
                 {
                     ModelState.AddModelError("Photo", "Shekilin olchusu max 200kb ola biler");
                     return View();
                 }
        
        
                 string path = Path.Combine("assets","img", "slider");
                 Helper.DeleteImage(_env.WebRootPath, path, dbSlider.Image);
              
        
                 string fileName = await createSliderVM.Photo.SaveImg(_env.WebRootPath, path);
                 dbSlider.Image = fileName;
        
             }
             dbSlider.Description = createSliderVM.Description;
             dbSlider.Title = createSliderVM.Title;
             
             await _context.SaveChangesAsync();
             return RedirectToAction(nameof(Index));
        }
    }

}

Areas/Admin/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Freedi Vugar Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">
    <link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/admin/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/admin/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand brand-logo" href="/Home/Index"><img src="~/assets/img/logo/logo-dark.jpg" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="/Home/Index"><img src="~/admin/images/logo-mini.svg" alt="logo" /></a>
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav mr-lg-4 w-100">
                    <li class="nav-item nav-search d-none d-lg-block w-100">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                            
                            <form class="form-inline position-relative">
                                <input class="form-control theme3" id="input-searchAdmin"
                                       placeholder="Enter your search key ..." style="width:400px">
                                <button class="btn bg-white search-btn position-left" type="submit">
                                    <i class="icon-magnifier"></i>
                                </button>
                            </form>
                            <div class="row" id="searchListAdmin" style="position:absolute;top:50px;background-color:white;z-index:1000;width:400px"></div>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">

                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            <img src="~/admin/images/faces/face5.jpg" alt="profile" />
                            <span class="nav-profile-name">@User.Identity.Name</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">


                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                @if (User.IsInRole("Admin"))
                {
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                            <span class="menu-title">Kateqoriya</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Brand" asp-action="Index">
                            <span class="menu-title">Brend</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">
                            <span class="menu-title">Mehsullar</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Sale" asp-action="Index">
                            <span class="menu-title">Sifarisler</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Sale" asp-action="FinishedSales">
                            <span class="menu-title">Satis olanlar</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Message" asp-action="Index">
                            <span class="menu-title">Mesajlar</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Subscription" asp-action="Index">
                            <span class="menu-title">Emailler</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Slider" asp-action="Index">
                            <span class="menu-title">Slider</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Banner" asp-action="Index">
                            <span class="menu-title">Banner</span>
                        </a>
                    </li>

                </ul>
                }

            </nav>

            <!-- partial -->
            <div class="main-panel">

                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
<!-- plugins:js -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/admin/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/admin/vendors/chart.js/Chart.min.js"></script>
    <script src="~/admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/admin/js/off-canvas.js"></script>
    <script src="~/admin/js/hoverable-collapse.js"></script>
    <script src="~/admin/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="~/admin/js/dashboard.js"></script>
    <script src="~/admin/js/data-table.js"></script>
    <script src="~/admin/js/jquery.dataTables.js"></script>
    <script src="~/admin/js/dataTables.bootstrap4.js"></script>
    <!-- End custom js for this page-->

    @RenderSection("Scripts", false)
    @RenderSection("Css", false)

</body>

</html>

Areas/Admin/Views/Shared/_partialAdminProduct.cshtml
@model IEnumerable<Product>

@foreach (var product in Model)
{
    <a class="dropdown-item"
       asp-area="Admin" asp-controller="Product" asp-action="Detail" asp-route-id="@product.Id">
        <div class="row">
            <div class="col-2 item-thumbnail" style="min-width:120px;">
                <img src="~/assets/img/product/@product.ProductImages.ElementAt(0).ImageUrl" alt="image" style="width:50px; height:50px" class="profile-pic">
            </div>
            <div class="col-2 item-content flex-grow" style="min-width:120px">
                <h6 class="ellipsis font-weight-normal" style="padding-top:15px;">
                    @product.Name
                </h6>
            </div>
            <div class="col-2" style="min-width:120px;">
                <h6 class="ellipsis font-weight-normal" style="padding-top:15px;">
                    $ @product.ResultPrice.ToString("C2")
                </h6>
            </div>
        </div>

    </a>
}

Areas/Admin/Views/Shared/_partialValidation.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>